load the dataset
waterbirds
get train set
[0 1 2 3]
Number of unique labels: 2, Number of unique places: 2, Total groups: 4
group 0: 3518
group 1: 185
group 2: 55
group 3: 1037
get valid set
[0 1 2 3]
Number of unique labels: 2, Number of unique places: 2, Total groups: 4
group 0: 456
group 1: 456
group 2: 143
group 3: 144
get test set
[0 1 2 3]
Number of unique labels: 2, Number of unique places: 2, Total groups: 4
group 0: 2255
group 1: 2255
group 2: 642
group 3: 642
no / wrong dataset
0
1
2
3
pruning indices  160
0
1
2
3
pruning indices (val) 160
Arch:vit_b_16
pruning_rates
[0, 0.001, 0.005, 0.001, 0.05, 0.1, 0.2, 0.3]
/home/primmere/.conda/envs/dfr2/lib/python3.10/site-packages/torch/autograd/graph.py:768: UserWarning: Attempting to run cuBLAS, but there was no current CUDA context! Attempting to set the primary context... (Triggered internally at ../aten/src/ATen/cuda/CublasHandlePool.cpp:135.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
Initial accuracy (val set): top1=0.34225060407317914
Initial worst accuracy (val set)=0.23902439024390243
Initial group accuracies (val set)={3: 0.4797507788161994, 2: 0.5124610591900312, 1: 0.3578713968957871, 0: 0.23902439024390243}
Processing 0% Pruning:  12%|█▎        | 1/8 [01:03<07:26, 63.72s/it]                      Traceback (most recent call last):
acc top1 (train) 0.35625
group accs (train) {2: 0.525, 0: 0.175, 3: 0.375, 1: 0.35}
Accuracy-Flow list (val): [0.34225060407317914]
Group accuracy (val): {3: 0.4797507788161994, 2: 0.5124610591900312, 1: 0.3578713968957871, 0: 0.23902439024390243}
Logged the results of 0% Pruning Rate to wandb!
/home/primmere/logs/pxp/results/0.1.pth
  File "/home/primmere/ide/external/pruning_by_explaining/my_experiments/my_global_pruning.py", line 315, in <module>
    start()
  File "/home/primmere/.conda/envs/dfr2/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/primmere/.conda/envs/dfr2/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/primmere/.conda/envs/dfr2/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/primmere/.conda/envs/dfr2/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/primmere/ide/external/pruning_by_explaining/my_experiments/my_global_pruning.py", line 239, in start
    hook_handles = pruner.fit_pruning_mask(
  File "/home/primmere/ide/external/pruning_by_explaining/pxp/prune.py", line 306, in fit_pruning_mask
    [
  File "/home/primmere/ide/external/pruning_by_explaining/pxp/prune.py", line 307, in <listcomp>
    super(GlobalPruningOperations, self).fit_pruning_mask(
  File "/home/primmere/ide/external/pruning_by_explaining/pxp/prune.py", line 60, in fit_pruning_mask
    bn_layer_name = conv_bn_layers[conv_bn_layers.index(layer_name) + 1]
ValueError: 'encoder.layers.encoder_layer_0.mlp.0' is not in list
Traceback (most recent call last):
  File "/home/primmere/ide/external/pruning_by_explaining/my_experiments/my_global_pruning.py", line 315, in <module>
    start()
  File "/home/primmere/.conda/envs/dfr2/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/primmere/.conda/envs/dfr2/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/primmere/.conda/envs/dfr2/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/primmere/.conda/envs/dfr2/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/primmere/ide/external/pruning_by_explaining/my_experiments/my_global_pruning.py", line 239, in start
    hook_handles = pruner.fit_pruning_mask(
  File "/home/primmere/ide/external/pruning_by_explaining/pxp/prune.py", line 306, in fit_pruning_mask
    [
  File "/home/primmere/ide/external/pruning_by_explaining/pxp/prune.py", line 307, in <listcomp>
    super(GlobalPruningOperations, self).fit_pruning_mask(
  File "/home/primmere/ide/external/pruning_by_explaining/pxp/prune.py", line 60, in fit_pruning_mask
    bn_layer_name = conv_bn_layers[conv_bn_layers.index(layer_name) + 1]
ValueError: 'encoder.layers.encoder_layer_0.mlp.0' is not in list
