load the dataset
no / wrong dataset
Traceback (most recent call last):
  File "/home/primmere/ide/external/pruning_by_explaining/my_experiments/my_global_pruning.py", line 307, in <module>
    start()
  File "/home/primmere/.conda/envs/dfr2/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/primmere/.conda/envs/dfr2/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/primmere/.conda/envs/dfr2/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/primmere/.conda/envs/dfr2/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/primmere/ide/external/pruning_by_explaining/my_experiments/my_global_pruning.py", line 102, in start
    train_set,
UnboundLocalError: local variable 'train_set' referenced before assignment
Traceback (most recent call last):
  File "/home/primmere/ide/external/pruning_by_explaining/my_experiments/my_global_pruning.py", line 307, in <module>
    start()
  File "/home/primmere/.conda/envs/dfr2/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/primmere/.conda/envs/dfr2/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/primmere/.conda/envs/dfr2/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/primmere/.conda/envs/dfr2/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/primmere/ide/external/pruning_by_explaining/my_experiments/my_global_pruning.py", line 102, in start
    train_set,
UnboundLocalError: local variable 'train_set' referenced before assignment
